apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: backend-deployment
  type: ClusterIP