services:
  
  backend:
    image: ghcr.io/djarnis2/simple-fortune-cookie-group18-backend:latest
    ports:
      - "9000:9000"
    environment:
      REDIS_DNS: redis
    depends_on:
      - redis

  frontend: 
    image: ghcr.io/djarnis2/simple-fortune-cookie-group18-frontend:latest
    ports:
      - "8080:8080"

    environment: 
      BACKEND_DNS: backend
      BACKEND_PORT: "9000"
    depends_on: 
      - backend
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

