services:
  
  backend-container:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  frontend-container: 
    build:  
      context: ./frontend 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"

    environment: 
      BACKEND_DNS: backend
      BACKEND_PORT: "9000"
    depends_on: 
      - backend-container

