name: CI/CD Pipeline
on: push
env:
  docker_username: ${{ github.repository_owner }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build-and-Test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.16"

      - name: Build backend
        run: | 
          cd backend
          go build 

      - name: Build Frontend
        run: |
          cd frontend
          go build

      - name: Run frontend tests
        run: |
          cd frontend
          go test ./... -v
          
  Linting:
    runs-on: ubuntu-latest
    needs: [Build-and-Test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run linting
      uses: super-linter/super-linter/slim@v7
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_ERRORS: "true"

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build-and-Test]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Login to GHCR
        run: echo "${{ env.docker_password }}" | docker login ghcr.io -u ${{ env.docker_username }} --password-stdin
      
      - name: build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.docker_username }}/simple-fortune-cookie-group18-backend:latest
      
      - name: build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ env.docker_username }}/simple-fortune-cookie-group18-frontend:latest

  Security-scan-images:
    runs-on: ubuntu-latest
    needs: [Docker-image]  
    steps:
    - name: Scan backend image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ env.docker_username }}/simple-fortune-cookie-group18-backend:latest

    - name: Scan frontend image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ env.docker_username }}/simple-fortune-cookie-group18-frontend:latest

                   
  Kubernetes-secrets-and-Deploy:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig kubeconfig apply -f backend-deployment.yaml
          kubectl --kubeconfig kubeconfig apply -f backend-service.yaml
          kubectl --kubeconfig kubeconfig apply -f frontend-deployment.yaml
          kubectl --kubeconfig kubeconfig apply -f frontend-service.yaml
          kubectl --kubeconfig kubeconfig apply -f redis-deployment.yaml
          kubectl --kubeconfig kubeconfig apply -f redis-service.yaml

  Kubernetes-Test:
    runs-on: ubuntu-latest
    needs: [Kubernetes-secrets-and-Deploy]
    steps:
      - name: Set up KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV
          
      - name: Forward backend port
        run: |
          for i in {1..10}; do
            kubectl --kubeconfig kubeconfig get svc/backend-deployment && break
            echo "Waiting for backend-deployment..."
            sleep 3
          done
          kubectl --kubeconfig kubeconfig get svc/backend-deployment || exit 1

          kubectl --kubeconfig kubeconfig port-forward svc/backend-deployment 9000:9000 &
          sleep 5

      - name: Test backend availability
        run: |
          curl -s http://localhost:9000/fortunes
          curl -X POST http://localhost:9000/fortunes \
            -H "Content-Type: application/json" \
            -d '{"id":"test1","message":"Redis test"}'
          curl -s http://localhost:9000/fortunes | grep "Redis test"

      
     
      
        
